export const categories = [
  { name: 'Coffee', slug: 'coffee' },
  { name: 'Tea', slug: 'tea' },
  { name: 'Cold Coffee', slug: 'cold-coffee' },
  { name: 'Cold Tea', slug: 'cold-tea' },
  { name: 'Shakes', slug: 'shakes' },
  { name: 'Smoothies', slug: 'smoothies' },
  { name: 'Mojito', slug: 'majito' },
  { name: 'Frappe', slug: 'frappe' },
  { name: 'Juice', slug: 'juice' },
  { name: 'Cakes', slug: 'cakes' },
  { name: 'Fruits', slug: 'fruits' },
  { name: 'Ice Cream', slug: 'ice-cream' },
  { name: 'Burger', slug: 'burger' },
  { name: 'Sandwiches', slug: 'sandwiches' },
  { name: 'BBQ', slug: 'bbq' },
  { name: 'Main Dishes', slug: 'main-dishes' },
]

const imageUrl = 'https://drive.google.com/uc?export=view&id='
export const items = [
  {
    categorySlug: 'coffee',
    name: 'Espresso',
    price: '$1.5',
    image: `${imageUrl}1LhIEfkSjbmZrsEKimlYU0L5kczyx-YQi`,
  },
  {
    categorySlug: 'coffee',
    name: 'Macchiato',
    price: '$1.5',
    image: `https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/2048px-No_image_available.svg.png`,
  },
  {
    categorySlug: 'coffee',
    name: 'Americano',
    price: '$1.5',
    image: `${imageUrl}1LWAQXWxK7uIx0ioiq-DiFVE8RA68QtsR`,
  },
  {
    categorySlug: 'coffee',
    name: 'Cappuccino',
    price: '$2',
    image: `${imageUrl}1o9d4os3YZbQ6Y_TlJ8HhuAkFHspwUkkm`,
  },
  {
    categorySlug: 'coffee',
    name: 'Coffee Late',
    price: '$2',
    image: `${imageUrl}1kO1pt3_TbvgYQaAjMA4hWqQ9_Nwo7dT3`,
  },
  {
    categorySlug: 'coffee',
    name: 'Coffee Mocha',
    price: '$2',
    image: `${imageUrl}1zG-_D7udJlNsIAS_gCQXVppPR5HqPiwA`,
  },
  {
    categorySlug: 'coffee',
    name: 'Turkish Coffee',
    price: '$1.5',
    image: `${imageUrl}1UyGDhG3HxVF8WeLKHBOTpIEmIC-UfsE3`,
  },
  {
    categorySlug: 'coffee',
    name: 'Hot chocolate',
    price: '$2.5',
    image: `https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/2048px-No_image_available.svg.png`,
  },
  {
    categorySlug: 'tea',
    name: 'Castello tea',
    price: '$3.5',
    image: `${imageUrl}1hVO5v6lV0aqQuipSKy-h_a6jQRxngKXG`,
  },
  {
    categorySlug: 'tea',
    name: 'Turkish tea',
    price: '$5',
    image: `${imageUrl}115KtEp1CfahhKT70FNV2DpmxEssWdWnm`,
  },
  {
    categorySlug: 'tea',
    name: 'Somali Tea',
    price: '$1',
    image: `https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/2048px-No_image_available.svg.png`,
  },
  {
    categorySlug: 'tea',
    name: 'Dawa tea',
    price: '$2',
    image: `https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/2048px-No_image_available.svg.png`,
  },
  {
    categorySlug: 'tea',
    name: 'Dhako jabiye tea',
    price: '$2',
    image: `https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/2048px-No_image_available.svg.png`,
  },
]
